### ISSUE TITLE
typescript import fails

### ISSUE THREAD

**Issue by listvin** [mrsteele/dotenv-defaults#75]
typescript project
`import "dotenv-defaults/config"`

gives
```stacktrace
/home/user/p/xxx/yyy/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366
    throw new ERR_MODULE_NOT_FOUND(
          ^
CustomError: Cannot find module '/home/user/p/xxx/yyy/node_modules/dotenv-defaults/config' imported from /home/user/p/xxx/yyy/src/index.ts
    at finalizeResolution (/home/user/p/xxx/yyy/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (/home/user/p/xxx/yyy/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/home/user/p/xxx/yyy/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /home/user/p/xxx/yyy/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/home/user/p/xxx/yyy/node_modules/ts-node/src/esm.ts:168:34)
    at /home/user/p/xxx/yyy/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/home/user/p/xxx/yyy/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/home/user/p/xxx/yyy/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
```

**Comment by listvin** [comment]
long story short it should be 
`import 'dotenv-defaults/config.js'`
probably should be mentioned in readme

**Comment by mrsteele** [comment]
Closing due to lack of participation.

Feel free to reopen this if you can provide more details, thanks.

**Comment by DogRespector93** [comment]
Seems like it may still be an issue.
